export const shopLots = [
  {
    url: "./images/shop-images/В'ялені-помідори_«Sottile_Gusto_Pomidory_Suszone».jpg",
    alt: "Sottile Gusto Pomidory Suszone",
    priceGRN: 50,
    priceUSDT: 2.48,
    nameUKR: "В'ялені помідори",
    nameEN: "Sottile Gusto Pomidory Suszone",
  },
  {
    url: "./images/shop-images/Паста_для_миття_рук_«Power_Wash_Hand_Washing_Cream».jpg",
    alt: "Power Wash Hand Washing Cream",
    priceGRN: 108,
    priceUSDT: 5.22,
    nameUKR: "Паста для миття рук",
    nameEN: "Power Wash Hand Washing Cream",
  },
  {
    url: "./images/shop-images/Гель_для_прання_«Ariel_Fresh_Sensations».jpg",
    alt: "Ariel Fresh Sensations",
    priceGRN: 195,
    priceUSDT: 9.33,
    nameUKR: "Гель для прання",
    nameEN: "Ariel Fresh Sensations",
  },
  {
    url: "./images/shop-images/Оливкова_олія_(каністра)_«Olio_Extra_Vergine_Di_Oliva».jpg",
    alt: "Olio Extra Vergine Di Oliva",
    priceGRN: 76,
    priceUSDT: 3.71,
    nameUKR: "Оливкова олія (каністра)",
    nameEN: "Olio Extra Vergine Di Oliva",
  },
  {
    url: "./images/shop-images/Плямовивідник_«Vanish_Oxi_Action».jpg",
    alt: "Vanish Oxi Action",
    priceGRN: 50,
    priceUSDT: 2.48,
    nameUKR: "Плямовивідник",
    nameEN: "Vanish Oxi Action",
  },
  {
    url: "./images/shop-images/Соус_«Univer_Erős_Pista».jpg",
    alt: "Univer Erős Pista",
    priceGRN: 39,
    priceUSDT: 1.95,
    nameUKR: "Соус",
    nameEN: "Univer Erős Pista",
  },
  {
    url: "./images/shop-images/Засіб_для_дезінфекції_«Astonish_Germ_Clean_Disinfectant».jpg",
    alt: "Astonish Germ Clean Disinfectant",
    priceGRN: 53,
    priceUSDT: 2.62,
    nameUKR: "Засіб для дезінфекції",
    nameEN: "Astonish Germ Clean Disinfectant",
  },
  {
    url: "./images/shop-images/Кукурудзяні_пластівці_«Smako_Corn_Flakes».jpg",
    alt: "Smako Corn Flakes",
    priceGRN: 37,
    priceUSDT: 1.86,
    nameUKR: "Кукурудзяні пластівці",
    nameEN: "Smako Corn Flakes",
  },
  {
    url: "./images/shop-images/Сіль_для_посудомийної_машини_«Denk_mit_Spezialsalz».jpg",
    alt: "Denk mit Spezialsalz",
    priceGRN: 53,
    priceUSDT: 2.62,
    nameUKR: "Сіль для посудомийної машини",
    nameEN: "Denk mit Spezialsalz",
  },
  {
    url: "./images/shop-images/Сосиски_«Yano_Hot_Dog».jpg",
    alt: "Yano Hot Dog",
    priceGRN: 60,
    priceUSDT: 2.95,
    nameUKR: "Сосиски",
    nameEN: "Yano Hot Dog",
  },
  {
    url: "./images/shop-images/Капсули_для_прання_«Dash_all_in_1_PODS».jpg",
    alt: "Dash all in 1 PODS",
    priceGRN: 242,
    priceUSDT: 11.55,
    nameUKR: "Капсули для прання",
    nameEN: "Dash all in 1 PODS",
  },
  {
    url: "./images/shop-images/Макарони_«Barilla_Fusilli_n.98».jpg",
    alt: "Barilla Fusilli n.98",
    priceGRN: 36,
    priceUSDT: 1.82,
    nameUKR: "Макарони",
    nameEN: "Barilla Fusilli n.98",
  },
  {
    url: "./images/shop-images/Засіб_для_миття_посуду_«Fairy_Original».jpg",
    alt: "Fairy Original",
    priceGRN: 27,
    priceUSDT: 1.39,
    nameUKR: "Засіб для миття посуду",
    nameEN: "Fairy Original",
  },
  {
    url: "./images/shop-images/Сир_фета_«Mlekovita_Favita».jpg",
    alt: "Mlekovita Favita",
    priceGRN: 32,
    priceUSDT: 1.63,
    nameUKR: "Сир фета",
    nameEN: "Mlekovita Favita",
  },
  {
    url: "./images/shop-images/Спрей_для_видалення_запаху_«W5_Textil_Erfrischer».jpg",
    alt: "W5 Textil Erfrischer",
    priceGRN: 50,
    priceUSDT: 2.48,
    nameUKR: "Спрей для видалення запаху",
    nameEN: "W5 Textil Erfrischer",
  },
  {
    url: "./images/shop-images/Оливки_«Contadina_Olive_Verdi_Dolce_Giganti».jpg",
    alt: "Contadina Olive Verdi Dolce Giganti",
    priceGRN: 61,
    priceUSDT: 3,
    nameUKR: "Оливки",
    nameEN: "Contadina Olive Verdi Dolce Giganti",
  },
];
