export const shopLots = [
  {
    url: "./images/shop-images/В'ялені-помідори_«Sottile_Gusto_Pomidory_Suszone».jpg",
    alt: "Sottile Gusto Pomidory Suszone",
    priceGRN: 50,
    priceUSDT: 2.48,
    nameUKR: "В'ялені помідори",
    nameEN: "&#171;Sottile Gusto Pomidory Suszone&#187;",
  },
  {
    url: "./images/shop-images/Паста_для_миття_рук_«Power_Wash_Hand_Washing_Cream».jpg",
    alt: "Power Wash Hand Washing Cream",
    priceGRN: 108,
    priceUSDT: 5.22,
    nameUKR: "Паста для миття рук",
    nameEN: "&#171;Power Wash Hand Washing Cream&#187;",
  },
  {
    url: "./images/shop-images/Гель_для_прання_«Ariel_Fresh_Sensations».jpg",
    alt: "Ariel Fresh Sensations",
    priceGRN: 195,
    priceUSDT: 9.33,
    nameUKR: "Гель для прання",
    nameEN: "&#171;Ariel Fresh Sensations&#187;",
  },
  {
    url: "./images/shop-images/Оливкова_олія_(каністра)_«Olio_Extra_Vergine_Di_Oliva».jpg",
    alt: "Olio Extra Vergine Di Oliva",
    priceGRN: 76,
    priceUSDT: 3.71,
    nameUKR: "Оливкова олія (каністра)",
    nameEN: "&#171;Olio Extra Vergine Di Oliva&#187;",
  },
  {
    url: "./images/shop-images/Плямовивідник_«Vanish_Oxi_Action».jpg",
    alt: "Vanish Oxi Action",
    priceGRN: 50,
    priceUSDT: 2.48,
    nameUKR: "Плямовивідник",
    nameEN: "&#171;Vanish Oxi Action&#187;",
  },
  {
    url: "./images/shop-images/Соус_«Univer_Erős_Pista».jpg",
    alt: "Univer Erős Pista",
    priceGRN: 39,
    priceUSDT: 1.95,
    nameUKR: "Соус",
    nameEN: "&#171;Univer Erős Pista&#187;",
  },
  {
    url: "./images/shop-images/Засіб_для_дезінфекції_«Astonish_Germ_Clean_Disinfectant».jpg",
    alt: "Astonish Germ Clean Disinfectant",
    priceGRN: 53,
    priceUSDT: 2.62,
    nameUKR: "Засіб для дезінфекції",
    nameEN: "&#171;Astonish Germ Clean Disinfectant&#187;",
  },
  {
    url: "./images/shop-images/Кукурудзяні_пластівці_«Smako_Corn_Flakes».jpg",
    alt: "Smako Corn Flakes",
    priceGRN: 37,
    priceUSDT: 1.86,
    nameUKR: "Кукурудзяні пластівці",
    nameEN: "&#171;Smako Corn Flakes&#187;",
  },
  {
    url: "./images/shop-images/Сіль_для_посудомийної_машини_«Denk_mit_Spezialsalz».jpg",
    alt: "Denk mit Spezialsalz",
    priceGRN: 53,
    priceUSDT: 2.62,
    nameUKR: "Сіль для посудомийної машини",
    nameEN: "&#171;Denk mit Spezialsalz&#187;",
  },
  {
    url: "./images/shop-images/Сосиски_«Yano_Hot_Dog».jpg",
    alt: "Yano Hot Dog",
    priceGRN: 60,
    priceUSDT: 2.95,
    nameUKR: "Сосиски",
    nameEN: "&#171;Yano Hot Dog&#187;",
  },
  {
    url: "./images/shop-images/Капсули_для_прання_«Dash_all_in_1_PODS».jpg",
    alt: "Dash all in 1 PODS",
    priceGRN: 242,
    priceUSDT: 11.55,
    nameUKR: "Капсули для прання",
    nameEN: "&#171;Dash all in 1 PODS&#187;",
  },
  {
    url: "./images/shop-images/Макарони_«Barilla_Fusilli_n.98».jpg",
    alt: "Barilla Fusilli n.98",
    priceGRN: 36,
    priceUSDT: 1.82,
    nameUKR: "Макарони",
    nameEN: "&#171;Barilla Fusilli n.98&#187;",
  },
];
